const OK_STATUS_CODE = 200
const VALIDATION_ERROR_CODE = 422
const CREATED_STATUS_CODE = 201
const UNAUTHORIZED_STATUS_CODE = 401
const SERVER_ERROR_STATUS_CODE = 500
const ACCEPTED_STATUS_CODE = 202
const NO_CONTENT = 204
const FORBIDDEN_STATUS_CODE = 403
const PAGE_NOT_FOUND_STATUS_CODE = 404


export {OK_STATUS_CODE, VALIDATION_ERROR_CODE, CREATED_STATUS_CODE, UNAUTHORIZED_STATUS_CODE, SERVER_ERROR_STATUS_CODE, ACCEPTED_STATUS_CODE, NO_CONTENT, FORBIDDEN_STATUS_CODE, PAGE_NOT_FOUND_STATUS_CODE};